# Site settings
title: My GitHub Page
description: Welcome to my GitHub Page!
theme: jekyll-theme-slate

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# GitHub Pages settings
remote_theme: "username/repo"
